server:
  port: 8999

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1/dg
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root


sms:
  gd:
    url: "http://211.100.62.140:9008/HttpQuickProcess/submitMessageAll"
    username: sydd
    password: sydd3
