server:
  port: 8081

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1/dg
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root


sms:
  gd:
    url: "xxxx"
    username: xxx
    password: yyy
